apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: motd-frontend
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=motd-frontend
spec:
  type: service
  lifecycle: experimental
  owner: motd-team
  system: motd
  dependsOn:
  - component:motd-backend
